// Mocks generated by Mockito 5.4.5 from annotations
// in party_planner/test/cubit/create_event_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i8;

import 'package:mockito/mockito.dart' as _i1;
import 'package:party_planner/src/core/models/event.dart' as _i2;
import 'package:party_planner/src/core/models/token.dart' as _i6;
import 'package:party_planner/src/core/models/ttrpg.dart' as _i3;
import 'package:party_planner/src/core/models/user.dart' as _i5;
import 'package:party_planner/src/core/models/user_profile.dart' as _i4;
import 'package:party_planner/src/core/services/calendar_service.dart' as _i10;
import 'package:party_planner/src/core/services/event_service.dart' as _i7;
import 'package:party_planner/src/core/services/ttrpg_service.dart' as _i9;
import 'package:party_planner/src/core/services/user_service.dart' as _i11;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventRead_0 extends _i1.SmartFake implements _i2.EventRead {
  _FakeEventRead_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventReadDetailed_1 extends _i1.SmartFake
    implements _i2.EventReadDetailed {
  _FakeEventReadDetailed_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeTTRPGRead_2 extends _i1.SmartFake implements _i3.TTRPGRead {
  _FakeTTRPGRead_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileRead_3 extends _i1.SmartFake implements _i4.ProfileRead {
  _FakeProfileRead_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPublic_4 extends _i1.SmartFake implements _i5.UserPublic {
  _FakeUserPublic_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToken_5 extends _i1.SmartFake implements _i6.Token {
  _FakeToken_5(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventsService extends _i1.Mock implements _i7.EventsService {
  MockEventsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i2.EventRead>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i8.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i8.Future<List<_i2.EventRead>>);

  @override
  _i8.Future<_i2.EventRead> createEvent(_i2.EventCreate? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i8.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i8.Future<_i2.EventRead>);

  @override
  _i8.Future<List<_i2.EventRead>> getMyEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [],
        ),
        returnValue: _i8.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i8.Future<List<_i2.EventRead>>);

  @override
  _i8.Future<void> joinEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i2.EventRead>> getMatchingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMatchingEvents,
          [],
        ),
        returnValue: _i8.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i8.Future<List<_i2.EventRead>>);

  @override
  _i8.Future<_i2.EventReadDetailed> getEventById(int? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue:
            _i8.Future<_i2.EventReadDetailed>.value(_FakeEventReadDetailed_1(
          this,
          Invocation.method(
            #getEventById,
            [eventId],
          ),
        )),
      ) as _i8.Future<_i2.EventReadDetailed>);

  @override
  _i8.Future<_i2.EventRead> finalizeEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #finalizeEvent,
          [eventId],
        ),
        returnValue: _i8.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #finalizeEvent,
            [eventId],
          ),
        )),
      ) as _i8.Future<_i2.EventRead>);
}

/// A class which mocks [TTRPGService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTTRPGService extends _i1.Mock implements _i9.TTRPGService {
  MockTTRPGService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<List<_i3.TTRPGRead>> getAllTTRPGs() => (super.noSuchMethod(
        Invocation.method(
          #getAllTTRPGs,
          [],
        ),
        returnValue: _i8.Future<List<_i3.TTRPGRead>>.value(<_i3.TTRPGRead>[]),
      ) as _i8.Future<List<_i3.TTRPGRead>>);

  @override
  _i8.Future<_i3.TTRPGRead> createTTRPG(_i3.TTRPGCreate? ttrpg) =>
      (super.noSuchMethod(
        Invocation.method(
          #createTTRPG,
          [ttrpg],
        ),
        returnValue: _i8.Future<_i3.TTRPGRead>.value(_FakeTTRPGRead_2(
          this,
          Invocation.method(
            #createTTRPG,
            [ttrpg],
          ),
        )),
      ) as _i8.Future<_i3.TTRPGRead>);
}

/// A class which mocks [CalendarService].
///
/// See the documentation for Mockito's code generation for more information.
class MockCalendarService extends _i1.Mock implements _i10.CalendarService {
  MockCalendarService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i8.Future<void> addEvent(_i2.EventCreate? event) => (super.noSuchMethod(
        Invocation.method(
          #addEvent,
          [event],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeEvent(String? eventId) => (super.noSuchMethod(
        Invocation.method(
          #removeEvent,
          [eventId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i11.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set token(String? _token) => super.noSuchMethod(
        Invocation.setter(
          #token,
          _token,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentUser(_i5.UserPublic? _currentUser) => super.noSuchMethod(
        Invocation.setter(
          #currentUser,
          _currentUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i8.Future<_i4.ProfileRead> createProfile(_i4.ProfileCreate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i8.Future<_i4.ProfileRead>.value(_FakeProfileRead_3(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i8.Future<_i4.ProfileRead>);

  @override
  _i8.Future<_i4.ProfileRead> getCurrentProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentProfile,
          [],
        ),
        returnValue: _i8.Future<_i4.ProfileRead>.value(_FakeProfileRead_3(
          this,
          Invocation.method(
            #getCurrentProfile,
            [],
          ),
        )),
      ) as _i8.Future<_i4.ProfileRead>);

  @override
  _i8.Future<_i4.ProfileRead> getUserProfile(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i8.Future<_i4.ProfileRead>.value(_FakeProfileRead_3(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i8.Future<_i4.ProfileRead>);

  @override
  _i8.Future<void> deleteUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.UserPublic> updateUser(
    int? id, {
    String? displayName,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [id],
          {
            #displayName: displayName,
            #password: password,
          },
        ),
        returnValue: _i8.Future<_i5.UserPublic>.value(_FakeUserPublic_4(
          this,
          Invocation.method(
            #updateUser,
            [id],
            {
              #displayName: displayName,
              #password: password,
            },
          ),
        )),
      ) as _i8.Future<_i5.UserPublic>);

  @override
  _i8.Future<_i4.ProfileRead> updateProfile(_i4.ProfileUpdate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i8.Future<_i4.ProfileRead>.value(_FakeProfileRead_3(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i8.Future<_i4.ProfileRead>);

  @override
  _i8.Future<void> saveUser(_i5.UserPublic? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<_i5.UserPublic?> loadUser() => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [],
        ),
        returnValue: _i8.Future<_i5.UserPublic?>.value(),
      ) as _i8.Future<_i5.UserPublic?>);

  @override
  _i8.Future<void> removeUser() => (super.noSuchMethod(
        Invocation.method(
          #removeUser,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<String?> loadToken() => (super.noSuchMethod(
        Invocation.method(
          #loadToken,
          [],
        ),
        returnValue: _i8.Future<String?>.value(),
      ) as _i8.Future<String?>);

  @override
  _i8.Future<void> saveToken(String? newToken) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [newToken],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);

  @override
  _i8.Future<List<_i5.UserPublic>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i8.Future<List<_i5.UserPublic>>.value(<_i5.UserPublic>[]),
      ) as _i8.Future<List<_i5.UserPublic>>);

  @override
  _i8.Future<_i5.UserPublic> getUserById(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i8.Future<_i5.UserPublic>.value(_FakeUserPublic_4(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i8.Future<_i5.UserPublic>);

  @override
  _i8.Future<_i5.UserPublic> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i8.Future<_i5.UserPublic>.value(_FakeUserPublic_4(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i8.Future<_i5.UserPublic>);

  @override
  _i8.Future<_i5.UserPublic> register(
    String? email,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            username,
            password,
          ],
        ),
        returnValue: _i8.Future<_i5.UserPublic>.value(_FakeUserPublic_4(
          this,
          Invocation.method(
            #register,
            [
              email,
              username,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i5.UserPublic>);

  @override
  _i8.Future<_i6.Token> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i8.Future<_i6.Token>.value(_FakeToken_5(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i8.Future<_i6.Token>);

  @override
  _i8.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i8.Future<void>.value(),
        returnValueForMissingStub: _i8.Future<void>.value(),
      ) as _i8.Future<void>);
}
