// Mocks generated by Mockito 5.4.5 from annotations
// in party_planner/test/cubit/event_details_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:party_planner/src/core/models/event.dart' as _i2;
import 'package:party_planner/src/core/models/token.dart' as _i5;
import 'package:party_planner/src/core/models/user.dart' as _i4;
import 'package:party_planner/src/core/models/user_profile.dart' as _i3;
import 'package:party_planner/src/core/services/event_service.dart' as _i6;
import 'package:party_planner/src/core/services/user_service.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventRead_0 extends _i1.SmartFake implements _i2.EventRead {
  _FakeEventRead_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventReadDetailed_1 extends _i1.SmartFake
    implements _i2.EventReadDetailed {
  _FakeEventReadDetailed_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeProfileRead_2 extends _i1.SmartFake implements _i3.ProfileRead {
  _FakeProfileRead_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPublic_3 extends _i1.SmartFake implements _i4.UserPublic {
  _FakeUserPublic_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToken_4 extends _i1.SmartFake implements _i5.Token {
  _FakeToken_4(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventsService extends _i1.Mock implements _i6.EventsService {
  MockEventsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<List<_i2.EventRead>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i7.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i7.Future<List<_i2.EventRead>>);

  @override
  _i7.Future<_i2.EventRead> createEvent(_i2.EventCreate? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i7.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i7.Future<_i2.EventRead>);

  @override
  _i7.Future<List<_i2.EventRead>> getMyEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [],
        ),
        returnValue: _i7.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i7.Future<List<_i2.EventRead>>);

  @override
  _i7.Future<void> joinEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i2.EventRead>> getMatchingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMatchingEvents,
          [],
        ),
        returnValue: _i7.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i7.Future<List<_i2.EventRead>>);

  @override
  _i7.Future<_i2.EventReadDetailed> getEventById(int? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue:
            _i7.Future<_i2.EventReadDetailed>.value(_FakeEventReadDetailed_1(
          this,
          Invocation.method(
            #getEventById,
            [eventId],
          ),
        )),
      ) as _i7.Future<_i2.EventReadDetailed>);

  @override
  _i7.Future<_i2.EventRead> finalizeEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #finalizeEvent,
          [eventId],
        ),
        returnValue: _i7.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #finalizeEvent,
            [eventId],
          ),
        )),
      ) as _i7.Future<_i2.EventRead>);
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i8.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set token(String? _token) => super.noSuchMethod(
        Invocation.setter(
          #token,
          _token,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentUser(_i4.UserPublic? _currentUser) => super.noSuchMethod(
        Invocation.setter(
          #currentUser,
          _currentUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i3.ProfileRead> createProfile(_i3.ProfileCreate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i3.ProfileRead>.value(_FakeProfileRead_2(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i3.ProfileRead>);

  @override
  _i7.Future<_i3.ProfileRead> getCurrentProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentProfile,
          [],
        ),
        returnValue: _i7.Future<_i3.ProfileRead>.value(_FakeProfileRead_2(
          this,
          Invocation.method(
            #getCurrentProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i3.ProfileRead>);

  @override
  _i7.Future<_i3.ProfileRead> getUserProfile(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i7.Future<_i3.ProfileRead>.value(_FakeProfileRead_2(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.ProfileRead>);

  @override
  _i7.Future<void> deleteUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.UserPublic> updateUser(
    int? id, {
    String? displayName,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [id],
          {
            #displayName: displayName,
            #password: password,
          },
        ),
        returnValue: _i7.Future<_i4.UserPublic>.value(_FakeUserPublic_3(
          this,
          Invocation.method(
            #updateUser,
            [id],
            {
              #displayName: displayName,
              #password: password,
            },
          ),
        )),
      ) as _i7.Future<_i4.UserPublic>);

  @override
  _i7.Future<_i3.ProfileRead> updateProfile(_i3.ProfileUpdate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i3.ProfileRead>.value(_FakeProfileRead_2(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i3.ProfileRead>);

  @override
  _i7.Future<void> saveUser(_i4.UserPublic? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i4.UserPublic?> loadUser() => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [],
        ),
        returnValue: _i7.Future<_i4.UserPublic?>.value(),
      ) as _i7.Future<_i4.UserPublic?>);

  @override
  _i7.Future<void> removeUser() => (super.noSuchMethod(
        Invocation.method(
          #removeUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> loadToken() => (super.noSuchMethod(
        Invocation.method(
          #loadToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> saveToken(String? newToken) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [newToken],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i4.UserPublic>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i7.Future<List<_i4.UserPublic>>.value(<_i4.UserPublic>[]),
      ) as _i7.Future<List<_i4.UserPublic>>);

  @override
  _i7.Future<_i4.UserPublic> getUserById(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i7.Future<_i4.UserPublic>.value(_FakeUserPublic_3(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i7.Future<_i4.UserPublic>);

  @override
  _i7.Future<_i4.UserPublic> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i7.Future<_i4.UserPublic>.value(_FakeUserPublic_3(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i7.Future<_i4.UserPublic>);

  @override
  _i7.Future<_i4.UserPublic> register(
    String? email,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            username,
            password,
          ],
        ),
        returnValue: _i7.Future<_i4.UserPublic>.value(_FakeUserPublic_3(
          this,
          Invocation.method(
            #register,
            [
              email,
              username,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i4.UserPublic>);

  @override
  _i7.Future<_i5.Token> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i7.Future<_i5.Token>.value(_FakeToken_4(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i5.Token>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}
