// Mocks generated by Mockito 5.4.5 from annotations
// in party_planner/test/cubit/home_tab_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:party_planner/src/core/models/event.dart' as _i2;
import 'package:party_planner/src/core/services/event_service.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEventRead_0 extends _i1.SmartFake implements _i2.EventRead {
  _FakeEventRead_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEventReadDetailed_1 extends _i1.SmartFake
    implements _i2.EventReadDetailed {
  _FakeEventReadDetailed_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [EventsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockEventsService extends _i1.Mock implements _i3.EventsService {
  MockEventsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i2.EventRead>> getAllEvents() => (super.noSuchMethod(
        Invocation.method(
          #getAllEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i4.Future<List<_i2.EventRead>>);

  @override
  _i4.Future<_i2.EventRead> createEvent(_i2.EventCreate? event) =>
      (super.noSuchMethod(
        Invocation.method(
          #createEvent,
          [event],
        ),
        returnValue: _i4.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #createEvent,
            [event],
          ),
        )),
      ) as _i4.Future<_i2.EventRead>);

  @override
  _i4.Future<List<_i2.EventRead>> getMyEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMyEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i4.Future<List<_i2.EventRead>>);

  @override
  _i4.Future<void> joinEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #joinEvent,
          [eventId],
        ),
        returnValue: _i4.Future<void>.value(),
        returnValueForMissingStub: _i4.Future<void>.value(),
      ) as _i4.Future<void>);

  @override
  _i4.Future<List<_i2.EventRead>> getMatchingEvents() => (super.noSuchMethod(
        Invocation.method(
          #getMatchingEvents,
          [],
        ),
        returnValue: _i4.Future<List<_i2.EventRead>>.value(<_i2.EventRead>[]),
      ) as _i4.Future<List<_i2.EventRead>>);

  @override
  _i4.Future<_i2.EventReadDetailed> getEventById(int? eventId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getEventById,
          [eventId],
        ),
        returnValue:
            _i4.Future<_i2.EventReadDetailed>.value(_FakeEventReadDetailed_1(
          this,
          Invocation.method(
            #getEventById,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i2.EventReadDetailed>);

  @override
  _i4.Future<_i2.EventRead> finalizeEvent(int? eventId) => (super.noSuchMethod(
        Invocation.method(
          #finalizeEvent,
          [eventId],
        ),
        returnValue: _i4.Future<_i2.EventRead>.value(_FakeEventRead_0(
          this,
          Invocation.method(
            #finalizeEvent,
            [eventId],
          ),
        )),
      ) as _i4.Future<_i2.EventRead>);
}
