// Mocks generated by Mockito 5.4.5 from annotations
// in party_planner/test/cubit/onboarding_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:mockito/mockito.dart' as _i1;
import 'package:party_planner/src/core/models/preference.dart' as _i5;
import 'package:party_planner/src/core/models/token.dart' as _i4;
import 'package:party_planner/src/core/models/user.dart' as _i3;
import 'package:party_planner/src/core/models/user_profile.dart' as _i2;
import 'package:party_planner/src/core/services/preference_service.dart' as _i8;
import 'package:party_planner/src/core/services/user_service.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeProfileRead_0 extends _i1.SmartFake implements _i2.ProfileRead {
  _FakeProfileRead_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeUserPublic_1 extends _i1.SmartFake implements _i3.UserPublic {
  _FakeUserPublic_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeToken_2 extends _i1.SmartFake implements _i4.Token {
  _FakeToken_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakePreferenceRead_3 extends _i1.SmartFake
    implements _i5.PreferenceRead {
  _FakePreferenceRead_3(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [UserService].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserService extends _i1.Mock implements _i6.UserService {
  MockUserService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  set token(String? _token) => super.noSuchMethod(
        Invocation.setter(
          #token,
          _token,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set currentUser(_i3.UserPublic? _currentUser) => super.noSuchMethod(
        Invocation.setter(
          #currentUser,
          _currentUser,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i7.Future<_i2.ProfileRead> createProfile(_i2.ProfileCreate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #createProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i2.ProfileRead>.value(_FakeProfileRead_0(
          this,
          Invocation.method(
            #createProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i2.ProfileRead>);

  @override
  _i7.Future<_i2.ProfileRead> getCurrentProfile() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentProfile,
          [],
        ),
        returnValue: _i7.Future<_i2.ProfileRead>.value(_FakeProfileRead_0(
          this,
          Invocation.method(
            #getCurrentProfile,
            [],
          ),
        )),
      ) as _i7.Future<_i2.ProfileRead>);

  @override
  _i7.Future<_i2.ProfileRead> getUserProfile(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getUserProfile,
          [userId],
        ),
        returnValue: _i7.Future<_i2.ProfileRead>.value(_FakeProfileRead_0(
          this,
          Invocation.method(
            #getUserProfile,
            [userId],
          ),
        )),
      ) as _i7.Future<_i2.ProfileRead>);

  @override
  _i7.Future<void> deleteUser(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #deleteUser,
          [userId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.UserPublic> updateUser(
    int? id, {
    String? displayName,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUser,
          [id],
          {
            #displayName: displayName,
            #password: password,
          },
        ),
        returnValue: _i7.Future<_i3.UserPublic>.value(_FakeUserPublic_1(
          this,
          Invocation.method(
            #updateUser,
            [id],
            {
              #displayName: displayName,
              #password: password,
            },
          ),
        )),
      ) as _i7.Future<_i3.UserPublic>);

  @override
  _i7.Future<_i2.ProfileRead> updateProfile(_i2.ProfileUpdate? profile) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateProfile,
          [profile],
        ),
        returnValue: _i7.Future<_i2.ProfileRead>.value(_FakeProfileRead_0(
          this,
          Invocation.method(
            #updateProfile,
            [profile],
          ),
        )),
      ) as _i7.Future<_i2.ProfileRead>);

  @override
  _i7.Future<void> saveUser(_i3.UserPublic? user) => (super.noSuchMethod(
        Invocation.method(
          #saveUser,
          [user],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i3.UserPublic?> loadUser() => (super.noSuchMethod(
        Invocation.method(
          #loadUser,
          [],
        ),
        returnValue: _i7.Future<_i3.UserPublic?>.value(),
      ) as _i7.Future<_i3.UserPublic?>);

  @override
  _i7.Future<void> removeUser() => (super.noSuchMethod(
        Invocation.method(
          #removeUser,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<String?> loadToken() => (super.noSuchMethod(
        Invocation.method(
          #loadToken,
          [],
        ),
        returnValue: _i7.Future<String?>.value(),
      ) as _i7.Future<String?>);

  @override
  _i7.Future<void> saveToken(String? newToken) => (super.noSuchMethod(
        Invocation.method(
          #saveToken,
          [newToken],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<void> removeToken() => (super.noSuchMethod(
        Invocation.method(
          #removeToken,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<List<_i3.UserPublic>> getUsers() => (super.noSuchMethod(
        Invocation.method(
          #getUsers,
          [],
        ),
        returnValue: _i7.Future<List<_i3.UserPublic>>.value(<_i3.UserPublic>[]),
      ) as _i7.Future<List<_i3.UserPublic>>);

  @override
  _i7.Future<_i3.UserPublic> getUserById(int? userId) => (super.noSuchMethod(
        Invocation.method(
          #getUserById,
          [userId],
        ),
        returnValue: _i7.Future<_i3.UserPublic>.value(_FakeUserPublic_1(
          this,
          Invocation.method(
            #getUserById,
            [userId],
          ),
        )),
      ) as _i7.Future<_i3.UserPublic>);

  @override
  _i7.Future<_i3.UserPublic> getCurrentUser() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUser,
          [],
        ),
        returnValue: _i7.Future<_i3.UserPublic>.value(_FakeUserPublic_1(
          this,
          Invocation.method(
            #getCurrentUser,
            [],
          ),
        )),
      ) as _i7.Future<_i3.UserPublic>);

  @override
  _i7.Future<_i3.UserPublic> register(
    String? email,
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [
            email,
            username,
            password,
          ],
        ),
        returnValue: _i7.Future<_i3.UserPublic>.value(_FakeUserPublic_1(
          this,
          Invocation.method(
            #register,
            [
              email,
              username,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i3.UserPublic>);

  @override
  _i7.Future<_i4.Token> login(
    String? username,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            username,
            password,
          ],
        ),
        returnValue: _i7.Future<_i4.Token>.value(_FakeToken_2(
          this,
          Invocation.method(
            #login,
            [
              username,
              password,
            ],
          ),
        )),
      ) as _i7.Future<_i4.Token>);

  @override
  _i7.Future<void> logout() => (super.noSuchMethod(
        Invocation.method(
          #logout,
          [],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);
}

/// A class which mocks [PreferencesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreferencesService extends _i1.Mock
    implements _i8.PreferencesService {
  MockPreferencesService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i5.PreferenceRead> createPreference(
          _i5.PreferenceCreate? preference) =>
      (super.noSuchMethod(
        Invocation.method(
          #createPreference,
          [preference],
        ),
        returnValue: _i7.Future<_i5.PreferenceRead>.value(_FakePreferenceRead_3(
          this,
          Invocation.method(
            #createPreference,
            [preference],
          ),
        )),
      ) as _i7.Future<_i5.PreferenceRead>);

  @override
  _i7.Future<_i5.PreferenceRead> getCurrentUserPreferences() =>
      (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserPreferences,
          [],
        ),
        returnValue: _i7.Future<_i5.PreferenceRead>.value(_FakePreferenceRead_3(
          this,
          Invocation.method(
            #getCurrentUserPreferences,
            [],
          ),
        )),
      ) as _i7.Future<_i5.PreferenceRead>);

  @override
  _i7.Future<_i5.PreferenceRead> getPreferenceById(int? preferenceId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferenceById,
          [preferenceId],
        ),
        returnValue: _i7.Future<_i5.PreferenceRead>.value(_FakePreferenceRead_3(
          this,
          Invocation.method(
            #getPreferenceById,
            [preferenceId],
          ),
        )),
      ) as _i7.Future<_i5.PreferenceRead>);

  @override
  _i7.Future<_i5.PreferenceRead> updatePreference(
    int? preferenceId,
    _i5.PreferenceUpdate? preference,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #updatePreference,
          [
            preferenceId,
            preference,
          ],
        ),
        returnValue: _i7.Future<_i5.PreferenceRead>.value(_FakePreferenceRead_3(
          this,
          Invocation.method(
            #updatePreference,
            [
              preferenceId,
              preference,
            ],
          ),
        )),
      ) as _i7.Future<_i5.PreferenceRead>);

  @override
  _i7.Future<void> deletePreference(int? preferenceId) => (super.noSuchMethod(
        Invocation.method(
          #deletePreference,
          [preferenceId],
        ),
        returnValue: _i7.Future<void>.value(),
        returnValueForMissingStub: _i7.Future<void>.value(),
      ) as _i7.Future<void>);

  @override
  _i7.Future<_i5.PreferenceRead> getPreferencesByUserId(int? userId) =>
      (super.noSuchMethod(
        Invocation.method(
          #getPreferencesByUserId,
          [userId],
        ),
        returnValue: _i7.Future<_i5.PreferenceRead>.value(_FakePreferenceRead_3(
          this,
          Invocation.method(
            #getPreferencesByUserId,
            [userId],
          ),
        )),
      ) as _i7.Future<_i5.PreferenceRead>);
}
